### PR TITLE
Extended description on oracle reliance

### PR DESCRIPTION
**Pull request by umersin61**
https://twitter.com/The3D_/status/1530540620082823170?s=20&t=MGDV_FY2NGC63H5Xo4nV3g

### CODE REVIEW

**Comment by eboadom** [comment]
@umersin61 
In my opinion, a message like the one proposed doesn't belong to that initial section of the developers' documentation page, mainly because following the organization on other documentation pages, it is expected to be a summary of the contract/component of the system. And more from a technical perspective.

That being said, I think it is a good idea to add more details than existing right now about oracle risks on Aave (maybe here? https://docs.aave.com/risk/asset-risk/price-discovery-requirements), but it should be in a more extensive way. 

Regarding the messaging, at the moment the PR is too simplistic: even if lately discussed quite frequently in public, the usage of a multi-sig is just another component, arguably way less important than plenty of other aspects, some of them even related to the multi-sig composition/nature itself. A risk section should mainly include an assessment from Aave's protocol perspective, together with linking to Chainlink's risk documentation and maybe highlighting some of the important points there, by repeating on the Aave's side.

About the PR procedure, please try to put a bit more rationale (why here in the docs, why those particular points, etc) next time, because it is a bit difficult to analyse the motivation just from a Twitter discussion.

**Comment by umersin61** [comment]
hey @eboadom, thanks for the feedback. I have the following points to make.

I think the AAVEOracle section needs more than a single line that states "We use Chainlink" and the main reason i put a simple explanation about what the implications of the use of Chainlink Aggregators means in there is, because i didn't want to touch your risk assessment section. 

The risk assessment section is something that individuals/institutions look at before making high stakes financial decisions. Personally, i don't feel comfortable adding something about risk in there without a risk or legal background that might be used from somebody to make multimillion $ decisions. This is the main reason i've asked somebody from AAVE that is responsible for risk to extend the risk section with Oracle Risk and what the Chainlink Multisig means for potential a) User Deposits and b) User Borrows. 

I also want to bring to your attention that there is no mention of any associated risk with Chainlink (and the Multisig) anywhere in your V3 docs and the "Risk Framework" for V1 & V2 from April 2021 states the following:

image

Not only are risks with Chainlink not spelled out, they are called "negligable" while referencing analysis that are partially written by Chainlink Members and it ends with saying nothing catastrophic happened so far. This report or the documentiation for V3 also makes no mention of the fact that while the AAVE protocols themselves are decentralized, they make use of heavily centralized components with great trust implications into a single entity and their ability to manage a multisig. 

The Ethos of "DeFi" is typically spelled out as "become your own bank" and something along the lines of "don't put your trust in a small group of people". I, as a heavy AAVE user, would like to it if it was pointed out to me that my funds are at the mercy of the Chainlink multisig, no matter how small the chance is that they would act maliciously. I don't think it is in your right to make the assessment for me if i think this is "risky" or not. The goal should be to spell out every possibility, no matter how unlikely it is, so that users can make fully informed financial decisions. 

This would also include adjusting this section that ignores the risk the multisig poses as well: https://docs.aave.com/faq/#is-there-any-risk

So the way forward here for me would be:
1. Get somebody from AAVE legal/risk to extend the Risk section in your documentation
2. (I can do this) Change this PR and add a line that links toward the risk implications of AAVE using Chainlink Aggregators.
3. (I can do this) Change the FAQ section "Is there any risk" with a summary of the multisig implications (link to the Risk section).
(Optional) 4. Add UI elements to AAVE that point towards the Risk section when users want to interact with the protocol. 

Happy to hear your feedback on this. 
Best,
Ugur

**Comment by eboadom** [comment]
Great set of suggestions @umersin61 . This well argumented feedback is perfect for the improvement of documentation and visibility in my opinion.

In general, I agree with your idea of expanding a bit the Risk section of the documentation and FAQ to try to cover extensively all the risks involved in the protocol.

Then, targeting that multi-sig as the primary point of failure of the system is not accurate, as it is reductionist (in its negative implications), so I think the Aave documentation should point to Chainlink resources explaining the technicalities of the system in their side (procedures, configuration, upgradeability, security, etc), for example [here](https://docs.chain.link/docs/using-chainlink-reference-contracts/#updates-to-proxy-and-aggregator-contracts).

I think the next steps, as you say, should be having a review (from Risk side of the community) about the documentation there, to see how/if improving it (probably it should a bit IMO). Together with maybe UI, but it is important to notice that there are a lot of different UIs accessing the Aave protocol, so that can only be done by best effort, and if the UI "maintainers" consider it appropriate, not me or you.

And regarding this PR, I think it should be closed because risk doesn't belong to developers' docs. Even more, I would review the documentation to check that there are no specific references and that the subject is kept purely technical. From the perspective of a developer, it simply doesn't matter any configuration on the side of integration as Chainlink.

**Comment by chrisblec** [comment]
> Then, targeting that multi-sig as the primary point of failure of the system is not accurate, as it is reductionist (in its negative implications)

@eboadom Can you advise what you mean by this? Isn't it true that if the Chainlink multisig is compromised that Aave will be adversely effected? It's not really reductionist. It's 100% accurate, isn't it? If so, then we shouldn't be obfuscating very clear, present and direct risks. We should be explicitly informing devs and end users as early in the Aave lifecycle as we possibly can.

**Comment by eboadom** [comment]
@chrisblec as I commented in my first message, is reductionist because the multi-signature wallet is another component of Chainlink's security infrastructure, an important one, but not more important than for example operational procedures during updates or any other system's modification.

As I said, it is pretty clear to me as a DeFi developer and Aave contributor that the way an external component is technically controlled doesn't belong to developers' documentation, because if for example, an integrator wants to test some functionality of the oracle, it will do it by using techniques like account impersonation. So I think it is perfectly reasonable to improve the Risk section with some extra details about the topic.

Now, I'm going to leave something really clear from my side. This kind of debate about the system's decentralization points is perfectly healthy, but I'm not willing to enter into dialectic battles, especially given that you personally are using what should be constructive discussions in a clearly weaponized way. One thing is being "adversarial", and another quite different is when even people participate in your discussions in a polite and friendly way, twisting their words for your own interest, whichever it is.

**Comment by chrisblec** [comment]
@eboadom Any single points of failure should be disclosed to devs who are considering integrating with Aave. This becomes even more important when they are external points of failure that are outside of the control of Aave, such as the multisig. Failure to integrate this language into the docs seems like a straight-up attempt to keep integrating devs from understanding the existential risk that these single points of failure may present to their own apps & protocols.

**Review by chrisblec — CHANGES_REQUESTED** [review]
Solid addition to the docs. Just run it through spell-check, a few misspellings to be fixed.

**Comment by foodaka** [comment]
Closing as per @eboadom suggestion that this will be added into the risk documentation

**Pull request closed without merging**
